name: biogas_umar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
